#cloud-config

hostname: node01

locale: en_US.UTF-8

system_info:
  default_user:
    name: satoshi

users:
  - name: bitcoin
    gecos: bitcoin system user
    shell: /bin/bash
    sudo: false

  - name: electrs
    gecos: electrs system user
    groups: bitcoin
    shell: /bin/bash
    sudo: false

  - name: btcexp
    gecos: BTC-RPC-Explorer system user
    groups: bitcoin
    shell: /bin/bash
    sudo: false

  - name: satoshi
    gecos: Node operator account
    groups: adm, bitcoin, cdrom, dip, lxd, plugdev, sudo
    shell: /bin/bash
    ssh_import_id: gh:1ma
    sudo: ALL=(ALL) NOPASSWD:ALL

write_files:
  - path: /etc/tor/torrc
    owner: root:root
    defer: true
    append: true
    permissions: '0644'
    content: |
      ControlPort 9051
      CookieAuthentication 1
      CookieAuthFileGroupReadable 1

      HiddenServiceDir /var/lib/tor/sshd/
      HiddenServiceVersion 3
      HiddenServicePort 22 127.0.0.1:22

      HiddenServiceDir /var/lib/tor/electrs/
      HiddenServiceVersion 3
      HiddenServicePort 50001 127.0.0.1:50001

      HiddenServiceDir /var/lib/tor/btc-rpc-explorer/
      HiddenServiceVersion 3
      HiddenServicePort 80 127.0.0.1:3002
  - path: /home/satoshi/.bitcoin/bitcoin.conf
    owner: satoshi:satoshi
    defer: true
    permissions: '0644'
    content: |
      datadir=/home/bitcoin/data
  - path: /home/bitcoin/bitcoin-setup.sh
    owner: bitcoin:bitcoin
    defer: true
    permissions: '0755'
    content: |
      #!/usr/bin/env bash

      set -euo pipefail

      export BITCOIN_VERSION=23.0
      export CFLAGS="-O2 --static -static -fPIC"
      export CXXFLAGS="-O2 --static -static -fPIC"
      export LDFLAGS="-s -static-libgcc -static-libstdc++"

      mkdir code data

      cd code
      wget -q https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/SHA256SUMS
      wget -q https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/SHA256SUMS.asc
      wget -q https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}.tar.gz

      # TODO that's trashy, rethink approach
      wget -q -O- https://raw.githubusercontent.com/1ma/dockertronics/master/bitcoin/developer_pubkeys.pem | gpg --import -

      gpg --verify SHA256SUMS.asc SHA256SUMS
      sha256sum --ignore-missing -c SHA256SUMS

      tar zxf bitcoin-${BITCOIN_VERSION}.tar.gz
      ./bitcoin-${BITCOIN_VERSION}/autogen.sh

      mkdir build
      cd build

      ../bitcoin-${BITCOIN_VERSION}/contrib/install_db4.sh $(pwd)

      export BDB_PREFIX="$(pwd)/db4"
      ../bitcoin-${BITCOIN_VERSION}/configure \
        BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" \
        BDB_CFLAGS="-I${BDB_PREFIX}/include" \
        --disable-bench \
        --disable-gui-tests \
        --disable-maintainer-mode \
        --disable-man \
        --disable-tests \
        --disable-zmq \
        --with-daemon=yes \
        --with-gui=no \
        --with-libmultiprocess=no \
        --with-libs=no \
        --with-miniupnpc=no \
        --with-mpgen=no \
        --with-natpmp=no \
        --with-qrencode=no \
        --with-utils=yes

      make -j$(nproc)
  - path: /home/bitcoin/bitcoin.conf
    owner: bitcoin:bitcoin
    defer: true
    permissions: '0600'
    content: |
      datadir=/home/bitcoin/data
      pid=/run/bitcoin/bitcoind.pid
      nodebuglogfile=1

      startupnotify=chmod g+r /home/bitcoin/data/.cookie

      assumevalid=0
      whitelist=download@127.0.0.1

      # Bitcoin daemon
      server=1
      txindex=1

      # Network
      listen=1
      listenonion=1
      proxy=127.0.0.1:9050
      bind=127.0.0.1
      i2psam=127.0.0.1:7656

      maxconnections=50
      maxuploadtarget=16384

      # Initial block download optimizations
      # Comment them out and restart after full sync
      dbcache=12288
      blocksonly=1

      # Barcelona Bitcoin Only community node
      addnode=jr77cwjarx5rba4x3hahafvjpkxdfuj7iiyctro47clguea7uzqhblad.onion:8333
  - path: /lib/systemd/system/bitcoin.service
    owner: root:root
    permissions: '0644'
    content: |
      [Unit]
      Description=Bitcoin daemon
      Documentation=https://github.com/bitcoin/bitcoin/blob/master/doc/init.md

      # https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
      After=network-online.target
      Wants=network-online.target electrs.service btcexp.service

      [Service]
      ExecStart=/usr/local/bin/bitcoind -conf=/home/bitcoin/bitcoin.conf

      # Process management
      ####################

      Type=exec
      PIDFile=/run/bitcoin/bitcoind.pid
      Restart=on-failure
      TimeoutStartSec=infinity
      TimeoutStopSec=600

      # Directory creation and permissions
      ####################################

      # Run as bitcoin:bitcoin
      User=bitcoin
      Group=bitcoin

      # /run/bitcoin
      RuntimeDirectory=bitcoin
      RuntimeDirectoryMode=0710

      # Hardening measures
      ####################

      # Provide a private /tmp and /var/tmp.
      PrivateTmp=true

      # Mount /usr, /boot/ and /etc read-only for the process.
      ProtectSystem=full

      # Disallow the process and all of its children to gain
      # new privileges through execve().
      NoNewPrivileges=true

      # Use a new /dev namespace only populated with API pseudo devices
      # such as /dev/null, /dev/zero and /dev/random.
      PrivateDevices=true

      # Deny the creation of writable and executable memory mappings.
      MemoryDenyWriteExecute=true

      [Install]
      WantedBy=multi-user.target
  - path: /etc/nginx/nginx.conf
    owner: root:root
    defer: true
    permissions: '0644'
    content: |
      user www-data;
      worker_processes auto;
      pid /run/nginx.pid;
      include /etc/nginx/modules-enabled/*.conf;

      events {
        worker_connections 768;
      }

      stream {
        ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout 4h;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        include /etc/nginx/streams-enabled/*.conf;
      }
  - path: /etc/nginx/streams-enabled/electrs-reverse-proxy.conf
    owner: root:root
    defer: true
    permissions: '0644'
    content: |
      upstream electrs {
        server 127.0.0.1:50001;
      }

      server {
        listen 50002 ssl;
        proxy_pass electrs;
      }
  - path: /run/electrs-setup.sh
    owner: root:root
    permissions: '0644'
    content: |
      #!/usr/bin/env bash

      set -euo pipefail

      export ELECTRS_VERSION=v0.9.10

      wget -q -O- https://romanzey.de/pgp.txt | gpg --import -

      cd /home/electrs
      git clone --branch ${ELECTRS_VERSION} https://github.com/romanz/electrs.git
      cd electrs
      git verify-tag ${ELECTRS_VERSION}

      cargo build --locked --release
      install -m 0755 -o root -g root -t /usr/local/bin ./target/release/electrs

      mkdir /home/electrs/data
      chown -R electrs:electrs /home/electrs

      systemctl enable electrs.service
  - path: /etc/electrs/electrs.conf
    owner: electrs:electrs
    defer: true
    permissions: '0644'
    content: |
      network = "bitcoin"
      daemon_dir= "/home/bitcoin/data"
      daemon_rpc_addr = "127.0.0.1:8332"
      daemon_p2p_addr = "127.0.0.1:8333"

      # Electrs settings
      electrum_rpc_addr = "127.0.0.1:50001"
      db_dir = "/home/electrs/data"

      # Logging
      log_filters = "INFO"
      timestamp = true
  - path: /lib/systemd/system/electrs.service
    owner: root:root
    permissions: '0644'
    content: |
      [Unit]
      Description=Electrs daemon
      After=bitcoin.service
      PartOf=bitcoin.service

      [Service]
      ExecStart=/usr/local/bin/electrs --conf /etc/electrs/electrs.conf

      Type=simple
      Restart=always
      TimeoutSec=120
      RestartSec=30
      KillMode=process

      User=electrs

      RuntimeDirectory=electrs
      RuntimeDirectoryMode=0710

      PrivateTmp=true
      PrivateDevices=true
      MemoryDenyWriteExecute=true

      [Install]
      WantedBy=multi-user.target
  - path: /etc/nginx/streams-enabled/btcexp-reverse-proxy.conf
    owner: root:root
    defer: true
    permissions: '0644'
    content: |
      upstream btcexp {
        server 127.0.0.1:3002;
      }
      server {
        listen 3003 ssl;
        proxy_pass btcexp;
      }
  - path: /run/btcexp-setup.sh
    owner: root:root
    permissions: '0644'
    content: |
      #!/usr/bin/env bash

      set -euo pipefail

      export BTCEXP_VERSION=v3.3.0

      wget -q -O- https://github.com/janoside.gpg | gpg --import -

      cd /home/btcexp
      git clone --branch ${BTCEXP_VERSION} https://github.com/janoside/btc-rpc-explorer.git
      cd btc-rpc-explorer
      git verify-commit ${BTCEXP_VERSION}

      cat <<'EOF' > .env
      BTCEXP_ADDRESS_API=electrum
      BTCEXP_BITCOIND_COOKIE=/home/bitcoin/data/.cookie
      BTCEXP_BITCOIND_HOST=127.0.0.1
      BTCEXP_BITCOIND_PORT=8332
      BTCEXP_BITCOIND_RPC_TIMEOUT=10000
      BTCEXP_ELECTRUM_SERVERS=tcp://127.0.0.1:50001
      BTCEXP_LOCAL_CURRENCY=eur
      BTCEXP_NO_RATES=false
      BTCEXP_PRIVACY_MODE=false
      BTCEXP_SLOW_DEVICE_MODE=false
      BTCEXP_UI_HIDE_INFO_NOTES=true
      BTCEXP_UI_THEME=dark
      EOF

      npm install

      chown -R btcexp:btcexp /home/btcexp

      systemctl enable btcexp.service
  - path: /lib/systemd/system/btcexp.service
    owner: root:root
    permissions: '0644'
    content: |
      [Unit]
      Description=BTC RPC Explorer
      After=bitcoin.service electrs.service
      PartOf=bitcoin.service

      [Service]
      WorkingDirectory=/home/btcexp/btc-rpc-explorer
      ExecStart=/usr/bin/npm start
      User=btcexp

      Restart=always
      RestartSec=30

      [Install]
      WantedBy=multi-user.target

apt_update: true
apt_upgrade: true

apt:
  sources:
    nodesource:
      source: "deb https://deb.nodesource.com/node_18.x jammy main"
      keyid: 9FD3 B784 BC1C 6FC3 1A8A 0A1C 1655 A0AB 6857 6280
    tor:
      source: "deb https://deb.torproject.org/torproject.org jammy main"
      keyid: A3C4 F0F9 79CA A22C DBA8 F512 EE8C BC9E 886D DD89
    i2pd:
      source: "ppa:purplei2p/i2pd"

packages:
  - autoconf
  - automake
  - build-essential
  - cargo
  - clang
  - cmake
  - fail2ban
  - git
  - i2pd
  - libboost-filesystem-dev
  - libboost-system-dev
  - libboost-thread-dev
  - libevent-dev
  - libsqlite3-dev
  - libtool
  - net-tools
  - nginx
  - nodejs
  - pkg-config
  - tmux
  - tor
  - ufw

runcmd:
  - adduser bitcoin debian-tor
  - su -c "bash -x /home/bitcoin/bitcoin-setup.sh" - bitcoin
  - make -C /home/bitcoin/code/build install
  - systemctl enable bitcoin.service
  - bash -x /run/electrs-setup.sh
  - bash -x /run/btcexp-setup.sh
  - openssl req -x509 -nodes -newkey rsa:4096 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/CN=localhost" -days 3650
  - nginx -t
  - systemctl enable i2pd.service
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw allow 3003/tcp comment 'allow BTC RPC Explorer SSL'
  - ufw allow 50002/tcp comment 'allow Electrum SSL'
  - ufw logging off
  - systemctl enable ufw.service
  - ufw enable

power_state:
  mode: reboot
