name: 'AutoNode CI/CD'

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: composer install
      - run: php vendor/bin/php-cs-fixer check --show-progress dots
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - ci
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: deployphp/action@v1
        with:
          dep: autonode:deploy
          private-key: ${{secrets.SSH_PRIVATE_KEY}}
          verbosity: -vv
