on:
  push:
    branches:
      - webapp
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy AutoNode
    runs-on: ubuntu-latest
    container: 1maa/php-dev:8.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies for deployment
        run: |
          apk add bash git openssh-client rsync
      - name: Run Deployer process
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.SSH_PRIVATE_KEY}}" | ssh-add -
          dep --file=deploy.php autonode:deploy -vv
